/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hotelreservationsystem;

/**
 *
 * @author Mikaela Padayachie
 */
public class ExecutiveRoomType extends javax.swing.JFrame {

    /**
     * Creates new form ExecutiveRoomType
     */
    public ExecutiveRoomType() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblExecutiveRoom = new javax.swing.JLabel();
        lblExecutiveRoomPicture = new javax.swing.JLabel();
        lblFeatures2 = new javax.swing.JLabel();
        lblFeatures = new javax.swing.JLabel();
        lblDescription = new javax.swing.JLabel();
        btnViewRoomOne = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        btnSelectRoomType = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblExecutiveRoom.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        lblExecutiveRoom.setForeground(new java.awt.Color(0, 0, 255));
        lblExecutiveRoom.setText("Executive Room - R1000 per night");

        lblExecutiveRoomPicture.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/BeachRoomThree.jpg"))); // NOI18N

        lblFeatures2.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        lblFeatures2.setForeground(new java.awt.Color(0, 0, 153));
        lblFeatures2.setText("private pool, private outdoor bed, unlimited WI-FI, direct access to ocean");

        lblFeatures.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        lblFeatures.setForeground(new java.awt.Color(0, 0, 153));
        lblFeatures.setText("Description:  King-sized bed, elegant en-suite bathroom with a spa bathtub, privatepterrace with panoramic ocean views, entertainment system,");

        lblDescription.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        lblDescription.setForeground(new java.awt.Color(0, 0, 153));
        lblDescription.setText("Description:  The pinnacle of refined accommodation, offering an exclusive and lavish stay.");

        btnViewRoomOne.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        btnViewRoomOne.setText("view room one");
        btnViewRoomOne.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewRoomOneActionPerformed(evt);
            }
        });

        btnBack.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        btnBack.setText("back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btnSelectRoomType.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        btnSelectRoomType.setText("select room type");
        btnSelectRoomType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelectRoomTypeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnBack)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnViewRoomOne)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSelectRoomType))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(lblFeatures, javax.swing.GroupLayout.PREFERRED_SIZE, 870, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(70, 70, 70)
                                .addComponent(lblExecutiveRoomPicture))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(267, 267, 267)
                                .addComponent(lblExecutiveRoom, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(212, 212, 212)
                                .addComponent(lblFeatures2, javax.swing.GroupLayout.PREFERRED_SIZE, 454, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(164, 164, 164)
                                .addComponent(lblDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 558, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 30, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(lblExecutiveRoom, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblExecutiveRoomPicture, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblFeatures, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblFeatures2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBack)
                    .addComponent(btnViewRoomOne)
                    .addComponent(btnSelectRoomType))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnViewRoomOneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewRoomOneActionPerformed
        new StandardRoomType().setVisible(true); // Takes user back to the StandardRoomType screen
        this.setVisible(false); // Closes this screen
    }//GEN-LAST:event_btnViewRoomOneActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        new DeluxeRoomType().setVisible(true);  // Takes user back to the DeluxeRoomType screen
        this.setVisible(false); // Closes this screen
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnSelectRoomTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelectRoomTypeActionPerformed
        new SelectRoomType().setVisible(true); // Takes user to the SelectRoomTypeScreen
        this.setVisible(false); // Closes this screen
    }//GEN-LAST:event_btnSelectRoomTypeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ExecutiveRoomType.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ExecutiveRoomType.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ExecutiveRoomType.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ExecutiveRoomType.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ExecutiveRoomType().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSelectRoomType;
    private javax.swing.JButton btnViewRoomOne;
    private javax.swing.JLabel lblDescription;
    private javax.swing.JLabel lblExecutiveRoom;
    private javax.swing.JLabel lblExecutiveRoomPicture;
    private javax.swing.JLabel lblFeatures;
    private javax.swing.JLabel lblFeatures2;
    // End of variables declaration//GEN-END:variables
}
