/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hotelreservationsystem;

/**
 *
 * @author mikae
 */
public class HowToLogIn extends javax.swing.JFrame {

    /**
     * Creates new form HowToLogIn
     */
    public HowToLogIn() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnOkay = new javax.swing.JButton();
        lblBackground3 = new javax.swing.JLabel();
        lblEditUsernameAndPassword2 = new javax.swing.JLabel();
        lblEditUsernameAndPassword3 = new javax.swing.JLabel();
        lblEditUsernameAndPassword4 = new javax.swing.JLabel();
        lblEditUsernameAndPassword5 = new javax.swing.JLabel();
        lblEditUsernameAndPassword6 = new javax.swing.JLabel();
        btnOkay1 = new javax.swing.JButton();
        lblBackground4 = new javax.swing.JLabel();

        btnOkay.setText("okay");
        btnOkay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOkayActionPerformed(evt);
            }
        });

        lblBackground3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/pure-white-background-85a2a7fd.jpg"))); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblEditUsernameAndPassword2.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        lblEditUsernameAndPassword2.setText("To log in, enter your username and password on the Log-In screen");

        lblEditUsernameAndPassword3.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        lblEditUsernameAndPassword3.setForeground(new java.awt.Color(0, 0, 255));
        lblEditUsernameAndPassword3.setText("HOW TO LOG-IN");

        lblEditUsernameAndPassword4.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        lblEditUsernameAndPassword4.setText("your own username and password (that you edited).");

        lblEditUsernameAndPassword5.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        lblEditUsernameAndPassword5.setText("For your first log-in, you will use the temporary username and ");

        lblEditUsernameAndPassword6.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        lblEditUsernameAndPassword6.setText("password generated for you. Hereafter, you can log-in with ");

        btnOkay1.setText("okay");
        btnOkay1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOkay1ActionPerformed(evt);
            }
        });

        lblBackground4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/pure-white-background-85a2a7fd.jpg"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(238, 238, 238)
                                .addComponent(lblEditUsernameAndPassword3, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addComponent(lblEditUsernameAndPassword2))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(100, 100, 100)
                                .addComponent(lblEditUsernameAndPassword4))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(66, 66, 66)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblEditUsernameAndPassword5)
                                    .addComponent(lblEditUsernameAndPassword6))))
                        .addGap(0, 42, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnOkay1)))
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(lblBackground4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 668, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(lblEditUsernameAndPassword3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblEditUsernameAndPassword2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblEditUsernameAndPassword5, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblEditUsernameAndPassword6, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblEditUsernameAndPassword4, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(btnOkay1)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(lblBackground4, javax.swing.GroupLayout.PREFERRED_SIZE, 279, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnOkayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOkayActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_btnOkayActionPerformed

    private void btnOkay1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOkay1ActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_btnOkay1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HowToLogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HowToLogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HowToLogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HowToLogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HowToLogIn().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOkay;
    private javax.swing.JButton btnOkay1;
    private javax.swing.JLabel lblBackground3;
    private javax.swing.JLabel lblBackground4;
    private javax.swing.JLabel lblEditUsernameAndPassword2;
    private javax.swing.JLabel lblEditUsernameAndPassword3;
    private javax.swing.JLabel lblEditUsernameAndPassword4;
    private javax.swing.JLabel lblEditUsernameAndPassword5;
    private javax.swing.JLabel lblEditUsernameAndPassword6;
    // End of variables declaration//GEN-END:variables
}
