/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hotelreservationsystem;

/**
 *
 * @author mikae
 */
public class HowToMakeAReservation extends javax.swing.JFrame {

    /**
     * Creates new form HowToMakeAReservation
     */
    public HowToMakeAReservation() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblEditUsernameAndPassword9 = new javax.swing.JLabel();
        lblEditUsernameAndPassword1 = new javax.swing.JLabel();
        lblEditUsernameAndPassword2 = new javax.swing.JLabel();
        lblEditUsernameAndPassword3 = new javax.swing.JLabel();
        lblEditUsernameAndPassword4 = new javax.swing.JLabel();
        lblEditUsernameAndPassword5 = new javax.swing.JLabel();
        lblEditUsernameAndPassword6 = new javax.swing.JLabel();
        lblEditUsernameAndPassword7 = new javax.swing.JLabel();
        lblEditUsernameAndPassword8 = new javax.swing.JLabel();
        lblEditUsernameAndPassword10 = new javax.swing.JLabel();
        lblEditUsernameAndPassword11 = new javax.swing.JLabel();
        lblEditUsernameAndPassword12 = new javax.swing.JLabel();
        lblBackground3 = new javax.swing.JLabel();
        btnOkay = new javax.swing.JButton();

        lblEditUsernameAndPassword9.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        lblEditUsernameAndPassword9.setText("Log In (Optional): Use your temporary username and password to log-in. Once logged in, you can cancel your reservation,  ");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblEditUsernameAndPassword1.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        lblEditUsernameAndPassword1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEditUsernameAndPassword1.setText("2. Press \"Make Reservation\":  Click on the \"Make a Reservation\" button on the Welcome Screen.");

        lblEditUsernameAndPassword2.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        lblEditUsernameAndPassword2.setForeground(new java.awt.Color(0, 0, 255));
        lblEditUsernameAndPassword2.setText("HOW TO MAKE A RESERVATION");

        lblEditUsernameAndPassword3.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        lblEditUsernameAndPassword3.setText("1. Welcome Screen:  Start at the Welcome Screen of your hotel reservation program");

        lblEditUsernameAndPassword4.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        lblEditUsernameAndPassword4.setText("6. Select Room Type: Choose the type of room you prefer from the available options.  ");

        lblEditUsernameAndPassword5.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        lblEditUsernameAndPassword5.setText("3. Check-In and Check-Out Screen: Select your desired check-in and check-out dates using the provided options.");

        lblEditUsernameAndPassword6.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        lblEditUsernameAndPassword6.setText("4. Personal and Contact Details Screen: Enter your personal information as required ");

        lblEditUsernameAndPassword7.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        lblEditUsernameAndPassword7.setText("5. Username and Password Screen: Here you will be given a temporary username and password to log in. Make note of it");

        lblEditUsernameAndPassword8.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        lblEditUsernameAndPassword8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEditUsernameAndPassword8.setText("7. Payment Screen: Enter your payment details as required ");

        lblEditUsernameAndPassword10.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        lblEditUsernameAndPassword10.setText("8. Payment Successful: Upon successful payment processing, you will receive a confirmation that your payment was successful. ");

        lblEditUsernameAndPassword11.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        lblEditUsernameAndPassword11.setText("review your reservation, and change your username as password");

        lblEditUsernameAndPassword12.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        lblEditUsernameAndPassword12.setText("9. Log In (Optional): Use your temporary username and password to log-in. Once logged in, you can cancel your reservation,  ");

        lblBackground3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/pure-white-background-85a2a7fd.jpg"))); // NOI18N

        btnOkay.setText("okay");
        btnOkay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOkayActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(135, 135, 135)
                        .addComponent(lblEditUsernameAndPassword3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addComponent(lblEditUsernameAndPassword1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(lblEditUsernameAndPassword5))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(122, 122, 122)
                        .addComponent(lblEditUsernameAndPassword6))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(lblEditUsernameAndPassword7))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(121, 121, 121)
                        .addComponent(lblEditUsernameAndPassword4))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(lblEditUsernameAndPassword10))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(276, 276, 276)
                        .addComponent(lblEditUsernameAndPassword2, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(28, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblEditUsernameAndPassword11)
                        .addGap(270, 270, 270))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnOkay)
                            .addComponent(lblEditUsernameAndPassword12))
                        .addGap(19, 19, 19))))
            .addGroup(layout.createSequentialGroup()
                .addGap(206, 206, 206)
                .addComponent(lblEditUsernameAndPassword8)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(lblBackground3, javax.swing.GroupLayout.PREFERRED_SIZE, 925, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(lblEditUsernameAndPassword2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblEditUsernameAndPassword3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblEditUsernameAndPassword1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblEditUsernameAndPassword5, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblEditUsernameAndPassword6, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblEditUsernameAndPassword7, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblEditUsernameAndPassword4, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(lblEditUsernameAndPassword8, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblEditUsernameAndPassword10, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblEditUsernameAndPassword12, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(lblEditUsernameAndPassword11, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnOkay)
                .addContainerGap(19, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(lblBackground3, javax.swing.GroupLayout.PREFERRED_SIZE, 488, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnOkayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOkayActionPerformed
       this.setVisible(false);
    }//GEN-LAST:event_btnOkayActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HowToMakeAReservation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HowToMakeAReservation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HowToMakeAReservation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HowToMakeAReservation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HowToMakeAReservation().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOkay;
    private javax.swing.JLabel lblBackground3;
    private javax.swing.JLabel lblEditUsernameAndPassword1;
    private javax.swing.JLabel lblEditUsernameAndPassword10;
    private javax.swing.JLabel lblEditUsernameAndPassword11;
    private javax.swing.JLabel lblEditUsernameAndPassword12;
    private javax.swing.JLabel lblEditUsernameAndPassword2;
    private javax.swing.JLabel lblEditUsernameAndPassword3;
    private javax.swing.JLabel lblEditUsernameAndPassword4;
    private javax.swing.JLabel lblEditUsernameAndPassword5;
    private javax.swing.JLabel lblEditUsernameAndPassword6;
    private javax.swing.JLabel lblEditUsernameAndPassword7;
    private javax.swing.JLabel lblEditUsernameAndPassword8;
    private javax.swing.JLabel lblEditUsernameAndPassword9;
    // End of variables declaration//GEN-END:variables
}
