/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hotelreservationsystem;

import javax.swing.JOptionPane;

/**
 *
 * @author Mikaela Padayachie
 */
public class StaffHomePage extends javax.swing.JFrame {

    private static String loggedInUsername;

    /**
     * Creates new form LogInScreenTwo
     *
     * @param username
     */
    public StaffHomePage(String username) {
        StaffHomePage.loggedInUsername = username;
        initComponents();
    }

    public StaffHomePage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblHelloStaffName = new javax.swing.JLabel();
        lblClickOnMenuButtonToSelectAction = new javax.swing.JLabel();
        lblHotelPicture = new javax.swing.JLabel();
        lblBackground = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuButton = new javax.swing.JMenu();
        menuItemViewAllReservations = new javax.swing.JMenuItem();
        menuItemAddNewStaffMember = new javax.swing.JMenuItem();
        menuItemEditStaffMember = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblHelloStaffName.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        lblHelloStaffName.setText("Hello,");

        lblClickOnMenuButtonToSelectAction.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        lblClickOnMenuButtonToSelectAction.setText("Please click on the menu button to select an action :) ");

        lblHotelPicture.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/hotel.jpg"))); // NOI18N

        lblBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/white background.jpg"))); // NOI18N

        menuButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        menuButton.setText("MENU");

        menuItemViewAllReservations.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        menuItemViewAllReservations.setText("VIEW ALL RESERVATIONS");
        menuItemViewAllReservations.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemViewAllReservationsActionPerformed(evt);
            }
        });
        menuButton.add(menuItemViewAllReservations);

        menuItemAddNewStaffMember.setText("ADD NEW STAFF MEMBER");
        menuItemAddNewStaffMember.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemAddNewStaffMemberActionPerformed(evt);
            }
        });
        menuButton.add(menuItemAddNewStaffMember);

        menuItemEditStaffMember.setText("EDIT EXISTING STAFF MEMBER");
        menuItemEditStaffMember.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemEditStaffMemberActionPerformed(evt);
            }
        });
        menuButton.add(menuItemEditStaffMember);

        jMenuBar1.add(menuButton);
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(lblClickOnMenuButtonToSelectAction))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(177, 177, 177)
                        .addComponent(lblHelloStaffName))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addComponent(lblHotelPicture)))
                .addContainerGap(52, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(lblBackground, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 565, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(lblHelloStaffName, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblClickOnMenuButtonToSelectAction, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblHotelPicture, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(46, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(lblBackground, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuItemEditStaffMemberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemEditStaffMemberActionPerformed
        // Fetches the staff member's username
        String staffUsername = loggedInUsername; // Assuming loggedInUsername is the staff member's username

        if (loggedInUsername != null) {
            // Opens the UsernamePasswordStaff form in edit mode with the user's ID
            UsernamePasswordStaff editStaffForm = new UsernamePasswordStaff();
            editStaffForm.setVisible(true);
            this.setVisible(false); // Close the current screen
        } else {
            // Handles the case where the user (staff member) was not found
            JOptionPane.showMessageDialog(this, "Staff member not found.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_menuItemEditStaffMemberActionPerformed

    private void menuItemAddNewStaffMemberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemAddNewStaffMemberActionPerformed
        new UsernamePasswordStaff().setVisible(true); // Takes user back to the WelcomeScreen
        this.setVisible(false); // Closes the screen once the user has made a selection
    }//GEN-LAST:event_menuItemAddNewStaffMemberActionPerformed

    private void menuItemViewAllReservationsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemViewAllReservationsActionPerformed
        new ReservationTable().setVisible(true); // Takes user  to the ReservationTable screen
        this.setVisible(false); // Closes this screen 
    }//GEN-LAST:event_menuItemViewAllReservationsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StaffHomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StaffHomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StaffHomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StaffHomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StaffHomePage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel lblBackground;
    private javax.swing.JLabel lblClickOnMenuButtonToSelectAction;
    private javax.swing.JLabel lblHelloStaffName;
    private javax.swing.JLabel lblHotelPicture;
    private javax.swing.JMenu menuButton;
    private javax.swing.JMenuItem menuItemAddNewStaffMember;
    private javax.swing.JMenuItem menuItemEditStaffMember;
    private javax.swing.JMenuItem menuItemViewAllReservations;
    // End of variables declaration//GEN-END:variables
}
